### ISSUE TITLE
Duda simple

### ISSUE THREAD

**Issue by ccolivares** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct12-music-api-grupo_n#1]
Buenas profesor, 

Tenemos una duda menor sobre la implementación de la práctica. Para pedir los datos al usuario por ejemplo a la hora de añadir nuevos elementos ¿Recomienda utilizar inquire, yargs o query string incluso para la inserción? (Entendemos que en la búsqueda interesa utilizar query string, pero nuestra duda es más a cerca de la inserción)

@esegredo

**Comment by ccolivares** [comment]
Buenas de nuevo,

Ya logramos entender como hacerlo, nos habiamos confundido.

Disculpe las molestias.

@esegredo

**Comment by esegredo** [comment]
De acuerdo Carla.

Saludos.
Eduardo
